tools.rust = "stable"
tasks.outdated = "cargo outdated --workspace --root-deps-only"
tasks.build = "cargo build --workspace"
tasks.test = "cargo test --workspace"
tasks.doc = "cargo doc --open"
tasks.clean = "cargo clean"
